
// Create room
POST  http://localhost:5000/api/room/createRoom
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmMWQxMjg5MmMyOTJkY2U5NDU4ZjIiLCJpYXQiOjE2OTM1Nzg3NDAsImV4cCI6MTY5NDQ0Mjc0MH0.5yAuQKNAHoQf7XmKxOJCeKra3_ZGKIAbJsqO1BscmRw
Content-Type:  application/json

{
     "name": "Test room 12",
    "visibility": "private",
    "members":[
      "64ef1ea452ecd120b6840e9d",
      "64ef1d12892c292dce9458f2",
      "64f33915205cd2de686d7365",
      "64f34873b47640f08f5ba564",
      "64f34878b47640f08f5ba567",
      "64f3487eb47640f08f5ba56b",
      "64f34882b47640f08f5ba56e",
      "64f34887b47640f08f5ba571"
    ]
}


###
GET   http://localhost:5000/api/room/getMyRooms
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmMWQxMjg5MmMyOTJkY2U5NDU4ZjIiLCJpYXQiOjE2OTM1Nzg3NDAsImV4cCI6MTY5NDQ0Mjc0MH0.5yAuQKNAHoQf7XmKxOJCeKra3_ZGKIAbJsqO1BscmRw


###
GET   http://localhost:5000/api/room/getMyOwnerRooms
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmMWQxMjg5MmMyOTJkY2U5NDU4ZjIiLCJpYXQiOjE2OTM1Nzg3NDAsImV4cCI6MTY5NDQ0Mjc0MH0.5yAuQKNAHoQf7XmKxOJCeKra3_ZGKIAbJsqO1BscmRw

###
GET   http://localhost:5000/api/user/getAllUsers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVmMWQxMjg5MmMyOTJkY2U5NDU4ZjIiLCJpYXQiOjE2OTM1Nzg3NDAsImV4cCI6MTY5NDQ0Mjc0MH0.5yAuQKNAHoQf7XmKxOJCeKra3_ZGKIAbJsqO1BscmRw

